name: test on push

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: start minikube
      id: minikube
      uses: medyagh/setup-minikube@latest

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'v1.21.0'

    - name: Apply Kubernetes manifests
      working-directory: ./04
      run: kubectl apply -f sample-pod.yml
